spring:
  application:
    name: meta-boot
  datasource:
    url: jdbc:mysql://192.168.1.159:3306/meta_boot?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.1.159
  data:
    mongodb:
      host: 192.168.1.159
      database: db
server:
  port: 8888
custom:
  property:
    path: classpath:prop/meta-${spring.profiles.active}.properties
elasticsearch:
  host: 192.168.1.159:9200
  cluster-name: docker-es
jwt:
  security:
    login: true
    ignore-urls: login
#服务注册地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.1.159:9000/eureka/
#  instance:
#    prefer-ip-address: true
#关闭安全控制，1.5.x版本以上默认开启
#management:
#  security:
#    enabled: false