spring:
  application:
    name: meta-boot
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/meta_boot?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1
  data:
    mongodb:
      host: 127.0.0.1
      database: db
server:
  port: 8888
custom:
  property:
    path: classpath:prop/meta-${spring.profiles.active}.properties
elasticsearch:
  host: 127.0.0.1:9200
  cluster-name: docker-es
jwt:
  security:
    login: true
    ignore-urls: login
logging:
  level:
    root: debug
jersey:
  swagger:
    ip: 192.168.1.188
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:9000/eureka/
#  instance:
#    prefer-ip-address: true
#management:
#  security:
#    enabled: false